### ISSUE TITLE
having problem

### ISSUE THREAD

**Issue by Jacobean0** [selim9445/yandex-mail-creator#2]
Im facing with error which is;

Traceback (most recent call last):
  File "main.py", line 8, in <module>
    yandex.create_account()
  File "/home/pi/Desktop/mail/mail/yandex.py", line 30, in create_account
    if self.get_element(By.CLASS_NAME, 'lg-cc__button_type_action') is not None:
  File "/home/pi/Desktop/mail/mail/webdriver.py", line 52, in get_element
    return self.driver.find_element(by, element)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"class name","selector":"lg-cc__button_type_action"}

**Comment by JakubZ0** [comment]
same here.
